name: Automate Leetcode problem tracking on Notion

on:
  push:
    branches:
      - main

jobs:
  update-notion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          
      - name: Initialize Go module
        run: |
          go mod init my-notion-sync || true
          go get golang.org/x/text/cases
          go get golang.org/x/text/language
      - name: Build and Run sync
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
        run: |
          go run .github/scripts/sync_notion.go
